version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
  this_job:
    docker:
      - image: circleci/python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["94:8f:63:4d:1a:d5:30:8b:a2:79:45:59:64:79:08:d3"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml  

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - this_job 
